### ISSUE TITLE
Syntax highlighting broken with typescript type literals and with simple elements like styled.div

### ISSUE THREAD

**Issue by maartenth** [styled-components/vscode-styled-components#159]
![screen shot 2019-03-04 at 10 37 53](https://user-images.githubusercontent.com/298893/53724505-511fba00-3e6a-11e9-8e8e-f7c82624779f.png)

#26 only added partial typescript support:

```ts
const StyledSection = styled.div<{ backgroundColor?: string }>` // no highlighting
const StyledSection = styled.div<Props>` // no highlighting
const StyledSection = styled<{ backgroundColor?: string }>('div')` // no highlighting
const StyledSection = styled<Props>('div')` // works
```

**Comment by chrisui** [comment]
I'm seeing the same. To clarify this only happens when using the generic version of the `div` function. Ie. `div<Props>()`.

**Comment by KostasLib** [comment]
Confirming that highlighting is broken when passing a type argument to the ```styled``` function. This behavior is not specific to type literals; passing any kind of type notation will break highlighting:

![capture2](https://user-images.githubusercontent.com/38813612/53833927-655ed680-3f92-11e9-8cdf-f9cf79fa9398.PNG)
![capture3](https://user-images.githubusercontent.com/38813612/53833943-6e4fa800-3f92-11e9-8d99-b693a1433284.PNG)

However, one way I got it to work, is to directly notate the Props type when consumed, at least once:

![capture5](https://user-images.githubusercontent.com/38813612/53834207-19606180-3f93-11e9-8a84-c0c3ce1035cb.PNG)
(works with destructuring as well)
![capture6](https://user-images.githubusercontent.com/38813612/53834210-1b2a2500-3f93-11e9-83a0-8d49ad5782bc.PNG)

This allows the compiler to infer the type without needing to explicitly pass a type argument as we tried before.

**Comment by kevinwolfcr** [comment]
Same for me, syntax highlight stopped properly working then typing my styled components.

### Before
<img width="411" alt="screenshot 2019-03-06 at 21 56 15" src="https://user-images.githubusercontent.com/3157426/53931486-f305f900-405a-11e9-872f-25774c022f96.png">

### After
<img width="412" alt="screenshot 2019-03-06 at 21 56 36" src="https://user-images.githubusercontent.com/3157426/53931497-05803280-405b-11e9-9a4c-c8c0996baf56.png">

**Comment by tomellwood** [comment]
I'm experiencing the same issue as stated above - syntax highlighting and css code completion is gone when using types.

Also as mentioned above, assigning a type directly to any of the props objects used within the styled component will fix type errors and keep syntax highlighting. However in this example, only `textMargin` would autocomplete after typing `p.`, and it doesn't seem ideal to have to repeat the `${(p: Types) => p.prop}` boilerplate for each rule that uses props.

![screen shot 2019-03-07 at 4 17 35 pm](https://user-images.githubusercontent.com/14232628/53971328-99eaa380-40f4-11e9-9587-e54d6d3a32e7.png)

**Comment by mrGibi** [comment]
to all: its finally fixed with 0.0.26 released today 🎉

**Comment by vviotto** [comment]
I still have a problem with this when using the styled function  even after 0.0.26 because 102f0d87d734f16bb8ec090bcbdfcd281150f817 doesnt take spaces into account

VSCode formatter automatically puts a space after the function, this breaks the highlight

![image](https://user-images.githubusercontent.com/42223067/55565755-cd5b2680-56d0-11e9-82f0-f5352fa574c9.png)

**Comment by GU5TAF** [comment]
Not sure if this is an error on my end but I still don't get syntax highlighting.

<img width="252" alt="Screenshot 2019-06-07 17 16 58" src="https://user-images.githubusercontent.com/3854323/59114805-46346400-8948-11e9-98f6-f5a75de51cf1.png">

**Comment by kimroen** [comment]
@GU5TAF It doesn't work with inline types like that, so create a type alias:

```ts
// Doesn't work
const MyComponent = styled.div<{ color: string }>``

// Works
type Props = { color: string };
const MyComponent = styled.div<Props>``;
```

It's just using a regex to detect things, so it can't really detect everything properly.

**Comment by GU5TAF** [comment]
> @GU5TAF It doesn't work with inline types like that, so create a type alias.
> It's just using a regex to detect things, so it can't really detect everything properly.

Okay, thanks for the reply! 🙏

**Comment by vitorrd** [comment]
It seems this does work with styled, but not with createGlobalStyle<>.

**Comment by willem-aart** [comment]
> It seems this does work with styled, but not with createGlobalStyle<>.

Same for `css<..>`

**Comment by jodapomo** [comment]
When the generic type is added also to the `attrs` the highlighting is still broken:

![image](https://user-images.githubusercontent.com/32148524/88471696-bcd84c00-ced1-11ea-8925-8247c7f5f991.png)

And if you declare the type directly in the `props` of the` attrs` call, you would lose access to the other properties, in this case `style`.

``` typescript
styled.div.attrs(({ size }: ContainerProps) => ({
  size: `${size}px`,
  style: { // <-- 'style' does not exist in type 'ContainerProps'
    height: `${size}px`,
  },
...
```

**Comment by basslagter** [comment]
I guess this one should be re-opened. Still issues with css<> and createGlobalStyle<>

**Comment by pixelkritzel** [comment]
Please reopen the issue. I have the same problem with `css`

**Comment by jasonwilliams** [comment]
We are looking for contributors, please see https://github.com/styled-components/vscode-styled-components/issues/275

**Comment by pixelkritzel** [comment]
@jasonwilliams I tried it but I didn't make it. The RegEx was stronger than me.

But my issues seems to be connected to a line break. If there isn't any line break it works as shown in the attached screenshots.

Maybe this will help somebody else.

![notworking](https://user-images.githubusercontent.com/1437379/110346990-6834ac00-8030-11eb-99a6-b5ab047048dd.png)
![working](https://user-images.githubusercontent.com/1437379/110347004-6cf96000-8030-11eb-9143-3af71ce71425.png)

**Comment by jasonwilliams** [comment]
Thanks @pixelkritzel that was useful

**Comment by johh** [comment]
Hey everyone, 
so I got the regex to pick up on multi-line inline types (https://regex101.com/r/XxGtKO/1/) but I'm a bit lost on how to proceed. Escaping and switching out the regex in `syntaxes/styled-components.json`, then building with `yarn vscode:prepublish`doesn't really do anything, at least when I install the extension locally. Am I missing something?

**Comment by johh** [comment]
> Hey everyone,
> so I got the regex to pick up on multi-line inline types (https://regex101.com/r/XxGtKO/1/) but I'm a bit lost on how to proceed. Escaping and switching out the regex in `syntaxes/styled-components.json`, then building with `yarn vscode:prepublish`doesn't really do anything, at least when I install the extension locally. Am I missing something?

@jasonwilliams, @finnp, do you know how to proceed? 🙂

**Comment by jasonwilliams** [comment]
> > Hey everyone,
> > so I got the regex to pick up on multi-line inline types (https://regex101.com/r/XxGtKO/1/) but I'm a bit lost on how to proceed. Escaping and switching out the regex in `syntaxes/styled-components.json`, then building with `yarn vscode:prepublish`doesn't really do anything, at least when I install the extension locally. Am I missing something?
> 
> @jasonwilliams, @finnp, do you know how to proceed? 🙂

Hmm how are you testing it? It should work. If you have this project checked out locally you should be able to hit “launch extension” in debug view on VSCode and test it on a file. Better yet you can create a test like the others and use that as a test.

**Comment by johh** [comment]
Thanks for your reply and for clearing things up! 
Launching it as you said, I still get no highlighting or autocomplete. 
![Screenshot 2021-03-20 at 22 38 34](https://user-images.githubusercontent.com/5791070/111886448-d5035b00-89cd-11eb-8c7f-6f0251af52ed.png)
I'm not too familiar with vscode extension development, how would I go about debugging this?

**Comment by jasonwilliams** [comment]
> @jasonwilliams I tried it but I didn't make it. The RegEx was stronger than me.
> 
> But my issues seems to be connected to a line break. If there isn't any line break it works as shown in the attached screenshots.
> 
> Maybe this will help somebody else.
> 
> ![notworking](https://user-images.githubusercontent.com/1437379/110346990-6834ac00-8030-11eb-99a6-b5ab047048dd.png)
> ![working](https://user-images.githubusercontent.com/1437379/110347004-6cf96000-8030-11eb-9143-3af71ce71425.png)

This has been fixed in [v1.5.1](https://github.com/styled-components/vscode-styled-components/releases/tag/v1.5.1) please let me know if it isn't

**Comment by Justkant** [comment]
Hi, there is still an issue when using styled options

![image](https://user-images.githubusercontent.com/3009753/116986608-4709d800-acce-11eb-8832-1136c3220df2.png)

I'm using the version 1.5.2

**Comment by jasonwilliams** [comment]
@Justkant any help on that one would be appreciated

**Comment by Justkant** [comment]
@jasonwilliams sure, how can I help ?

I'm using emotion and I just saw that `styled-components` and `emotion` differ on the way you specify the `shouldForwardProp` option. ([styled](https://styled-components.com/docs/api#shouldforwardprop) vs [emotion](https://emotion.sh/docs/styled#customizing-prop-forwarding))

I also had a look at the multiline fix (https://github.com/styled-components/vscode-styled-components/pull/281) and I haven't had the time to test some changes to the regex

In the meantime, here is a fixture for my issue:
```ts
interface StyledBrokenProps = {
    multipleLines: boolean;
}

const StyledBroken = styled('h1', {
  shouldForwardProp: prop => prop !== 'multipleLines'
})<StyledBrokenProps>`
    background: red;
`;
```

**Comment by jasonwilliams** [comment]
@Justkant you should be able to clone this repo, hit “lunch extension” in the debug tab. That will load a second VSCode instance with the fixtures folder loaded.

Go into a typescript fixture (doesn’t matter which one) and replace it with your fixture.

now take one of the regexes (it’s this one https://github.com/styled-components/vscode-styled-components/blob/master/syntaxes/styled-components.json#L159) and tweak it. You can do that by throwing it into regex101 (Unescape it first) and put your fixture in Regex 101 aswell. Then you can tweak there.

once you’re happy load it back into the json file (escaped) and hit refresh on the debug bar.

**Comment by jasonwilliams** [comment]
@Justkant if you're stuck at any point, let me know.

**Comment by Justkant** [comment]
Hi, sorry I hadn't much time to try and fix this issue lately.

I did try today and found a tweak on Regex 101 that helped but couldn't make it work when debugging the extension in vscode.
I also found some inconsistencies when debugging with the [Scope Inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector)

I'll add more infos later when I have some time

**Comment by jasonwilliams** [comment]
Feel free to share the tweak you did on Regex 101 I can probably take a look

**Comment by pixelkritzel** [comment]
> > @jasonwilliams I tried it but I didn't make it. The RegEx was stronger than me.
> > But my issues seems to be connected to a line break. If there isn't any line break it works as shown in the attached screenshots.
> > Maybe this will help somebody else.
> > ![notworking](https://user-images.githubusercontent.com/1437379/110346990-6834ac00-8030-11eb-99a6-b5ab047048dd.png)
> > ![working](https://user-images.githubusercontent.com/1437379/110347004-6cf96000-8030-11eb-9143-3af71ce71425.png)
> 
> This has been fixed in [v1.5.1](https://github.com/styled-components/vscode-styled-components/releases/tag/v1.5.1) please let me know if it isn't

Just saw your comment. Yes, it works for this usecase with styled-components. Thank you!

**Comment by orenklein** [comment]
@jasonwilliams
Now in the case of types in new lines - the styles highlighting is working but it messes up everything afterwards
Before adding new lines:
![image](https://user-images.githubusercontent.com/21295634/146923788-8083fa81-8bd5-4d75-9def-3d215c7391c8.png)

After adding new lines
![image](https://user-images.githubusercontent.com/21295634/146923731-0d453313-65e2-4375-b10c-7cb7c5e1c543.png)

**Comment by Otoris** [comment]
Same issue here. Unsure if it's me or a change needed to the syntax highlighting?

![Screen Shot 2022-05-05 at 3 26 48 PM](https://user-images.githubusercontent.com/360427/167010810-698ee9cd-a36f-4bff-a1c7-b6d5e1acb62f.png)

**Comment by WDeenik** [comment]
Still have this issue when styling components and providing a multi-line props type:

```
const Styled = styled(UnstyledComponent)<{
  someValue: number;
  someProp: string;
}>` // Highlighting breaks

const Styled2 = styled(UnstyledComponent)<{someValue: number; someProp: string;}>` // Highlighting still works

const Styled3 = styled.div<{
  someValue: number;
  someProp: string;
}>` // Highlighting still works
```
