### ISSUE TITLE
Highlighting breaks when extract props in typescript

### ISSUE THREAD

**Issue by l3lock** [styled-components/vscode-styled-components#229]
Highlighting breaks when passing custom props to [styled-component](https://styled-components.com/docs/api#typescript) by extract some props like this image
![image](https://user-images.githubusercontent.com/18025306/90542213-f38e4300-e1ad-11ea-9ed5-9f3f49ddbffc.png)

**Comment by burns-brian** [comment]
I believe I am having the same issue. Here is another example:

```
import { ThemeType } from './theme'

const Base = createGlobalStyle<{ theme: ThemeType }>``
```

It looks like the `<>` before the tagged template breaks the syntax highlighting in Typescript.

**Comment by burns-brian** [comment]
I believe I am having the same issue. Here is another example:

```
import { ThemeType } from './theme'

const Base = createGlobalStyle<{ theme: ThemeType }>``
```

It looks like the `<>` before the tagged template breaks the syntax highlighting in Typescript.

**Visual Result:**

<img width="735" alt="Screen Shot 2020-08-27 at 6 16 21 PM" src="https://user-images.githubusercontent.com/13523868/91500645-e3532380-e891-11ea-9bdb-4e464677929f.png">

**Comment by Tbaut** [comment]
Any visibility on this problem? Using theme makes this extension worthless unfortunately.

**Comment by jasonwilliams** [comment]
@umanghome

**Comment by umanghome** [comment]
I'll look into this.

**Comment by umanghome** [comment]
This is what I see on the current master. Assuming that the issue reported by @burns-brian has been fixed. 
![image](https://user-images.githubusercontent.com/5698706/96380580-4c2d8c80-11ad-11eb-93a8-6211e7a6b053.png)

**Comment by umanghome** [comment]
@l3lock's issue seems to have been fixed too.

![image](https://user-images.githubusercontent.com/5698706/96382104-dd9cfe80-11ad-11eb-893d-28b48aafc034.png)

```ts
const Notification = styled(({ active, activeColor, ...rest }) => <Badge {...rest} />)<ActiveProps & BadgeProps>`
  border: 0;
  max-width: 100%;
`;
```

**Comment by Tbaut** [comment]
I'm on the latest release (v1.1.0 from 4 days ago) in a tsx file and the problem is still there
![image](https://user-images.githubusercontent.com/33178835/96419051-e3b5ce00-11f3-11eb-956e-9a62cd75b1f0.png)

**Comment by burns-brian** [comment]
> I believe I am having the same issue. Here is another example:
> 
> ```
> import { ThemeType } from './theme'
> 
> const Base = createGlobalStyle<{ theme: ThemeType }>``
> ```
> 
> It looks like the `<>` before the tagged template breaks the syntax highlighting in Typescript.
> 
> **Before:**
> 
> <img alt="Screen Shot 2020-08-27 at 6 20 33 PM" width="735" src="https://user-images.githubusercontent.com/13523868/91500741-11386800-e892-11ea-9841-9cab2fe802e5.png">
> 
> **After:**
> 
> <img alt="Screen Shot 2020-08-27 at 6 16 21 PM" width="735" src="https://user-images.githubusercontent.com/13523868/91500645-e3532380-e891-11ea-9bdb-4e464677929f.png">

I just wanted to state for the record that it looks like my specific issue got fixed. My original post was on Aug. 27th. I am currently running v1.1.0 now. Thanks for any update that was made to address the issue!

**Comment by l3lock** [comment]
@burns-brian it works fine for me
![Screen Shot 2563-10-21 at 11 23 10 AM](https://user-images.githubusercontent.com/18025306/96673100-f1a05600-138f-11eb-9cbe-c8b44753e582.png)

**Comment by l3lock** [comment]
@burns-brian this works fine for me

![Screen Shot 2563-10-21 at 11 38 55 AM](https://user-images.githubusercontent.com/18025306/96674011-0251cb80-1392-11eb-9c81-9b455b844dae.png)

**Comment by Tbaut** [comment]
As mentioned in https://github.com/styled-components/vscode-styled-components/issues/229#issuecomment-711815435 the problem is still present for me, on v1.2.0, note that my test is on a styled exported component, with a super simple syntax:

```js
export default styled(Table)(({ theme }: ThemeProps) => `
  border: 0;
  display: block;
  font-size: ${theme.labelFontSize};
  line-height: ${theme.labelLineHeight};
  margin-bottom: 1rem;
`);
```

**Comment by jasonwilliams** [comment]
@Tbaut would you be up for having a go at fixing this? We have a contributing guide here:
https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by Tbaut** [comment]
Yes, I want to see how far I can go there. I'll try to give it a shot in the next days.

**Comment by Tbaut** [comment]
I've been unable to solve the problem.

I've added a `ts-props-import` test that should pass for the bug to be fixed, visible [here](https://github.com/Tbaut/vscode-styled-components/blob/tbaut-ts-props/src/tests/suite/colorize-fixtures/typescript-props-import.ts) ([ and here the corresponding expected result](https://github.com/Tbaut/vscode-styled-components/blob/tbaut-ts-props/src/tests/suite/colorize-results/typescript-props-import_ts.json))

Since the same test snippet, with an additionnal `<SomeType>` works well, I thought the problem would be in the regex [at this line](https://github.com/styled-components/vscode-styled-components/blob/master/syntaxes/styled-components.json#L7), where some `<.+>` would be required. However, toward the end of the line, this part seems indeed non obligatory):
```
... ((.+)\\))(?:\\s*<.+>)?)|(css|keyframes ...
                    ^^^^---here
```

So it doesn't seem to be the origin of the problem. Also something I am surprised about, in the following gif, I'm running an unmodified 1.3.0 version of the extension, and by just adding one `<` suffice to make the highlight work, no need of `SomeType>`:

![styled](https://user-images.githubusercontent.com/33178835/99951137-e02adf00-2d7d-11eb-8e25-6557dcc5c834.gif)

Based on the above regex, I would have expected the highlight to fail until I write the full `<SomeType>`. Any pointer would be appreciated.

**Comment by jasonwilliams** [comment]
Paging @umanghome are you able to help with the above?

**Comment by finnp** [comment]
I checked the examples in this issue and they all worked for me.  If there's still problems in some cases let's open a new issue for that.
