### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by umanghome** [styled-components/vscode-styled-components#234]
I'm trying to fix #233. I cloned the repo and ran `npm run test` - and it modified all the files in `test/colorize-results` directory. I don't think this should happen. Are the tests out of date? Am I doing something wrong while running tests?

It would be really nice to have a contribution guide which can, if not answer these questions, point me in a correct direction on how to add fixes/features.

**Comment by jasonwilliams** [comment]
Hey @mjbvz do you know how these tests were supposed to work? They seem outdated and im not sure if this is how the extension should properly test these days

**Comment by jasonwilliams** [comment]
@umanghome please try again on the rebased master. The tests should now work.
There is now a contributing guide here: https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by umanghome** [comment]
Thanks! That should help a lot.

**Comment by umanghome** [comment]
@jasonwilliams Tests still don't work for me on local. I passed the `--disable-extensions` flag as well, but four tests fail. I saw CI is using Node 12, and I tried running tests on the same version as CI. That didn't work either.

These are the changes that it makes when tests fail: https://github.com/umanghome/vscode-styled-components/commit/3357446b0cf89e0c4be680f77eb2cc872b904e4b

**Comment by umanghome** [comment]
Looks like this is because I have
```json
"editor.tokenColorCustomizations": {
  "comments": "#000000"
}
```
in my VS code settings.

My VS Code settings shouldn't affect tests. I'm not sure if this is a VS Code issue.

**Comment by jasonwilliams** [comment]
That will definitely be it, changing tokens will most likely break the tests as they check the token output.

You should remove that for the instance that’s running the tests.
